import {auth,db,onAuthStateChanged,signOut,collection,doc,getDocs,getDoc,setDoc,serverTimestamp} from './firebase.js';
export const $=id=>document.getElementById(id); export const today=()=>new Date().toISOString().slice(0,10); export const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
export const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
export const fmtDate=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'Unknown';
export const userCollection=(uid,name)=>collection(db,'users',uid,name); export const userDoc=(uid,name,id)=>doc(db,'users',uid,name,id);
export async function loadCollection(uid,name){const s=await getDocs(userCollection(uid,name));return s.docs.map(d=>({id:d.id,...d.data()}));}
export async function loadSettings(uid){const s=await getDoc(doc(db,'users',uid,'profile','settings'));return {unit:'kg',measureUnit:'cm',defaultReps:10,defaultSets:3,weightStep:2.5,defaultRest:60,autoRest:false,heightCm:169,...(s.exists()?s.data():{})};}
export async function saveSettings(uid,value){await setDoc(doc(db,'users',uid,'profile','settings'),{...value,updatedAt:serverTimestamp()},{merge:true});}
export function requireAuth(callback){onAuthStateChanged(auth,user=>{if(!user){location.href='/';return;}document.querySelectorAll('[data-user-email]').forEach(e=>e.textContent=user.email||'Signed in');document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=()=>signOut(auth).then(()=>location.href='/'));callback(user);});}
export function drawChart(canvas,points){const c=canvas.getContext('2d'),w=canvas.clientWidth||600,h=260,r=devicePixelRatio||1;canvas.width=w*r;canvas.height=h*r;c.scale(r,r);c.clearRect(0,0,w,h);if(!points.length){c.fillStyle='#746b77';c.font='15px system-ui';c.fillText('No data yet',20,35);return;}const p={l:42,r:15,t:18,b:34},vals=points.map(x=>num(x.value));let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}const x=i=>p.l+(points.length===1?(w-p.l-p.r)/2:i*(w-p.l-p.r)/(points.length-1));const y=v=>p.t+(max-v)*(h-p.t-p.b)/(max-min);c.strokeStyle='#dfd4e2';for(let i=0;i<4;i++){let yy=p.t+i*(h-p.t-p.b)/3;c.beginPath();c.moveTo(p.l,yy);c.lineTo(w-p.r,yy);c.stroke()}c.strokeStyle='#7c3f91';c.lineWidth=3;c.beginPath();points.forEach((q,i)=>i?c.lineTo(x(i),y(q.value)):c.moveTo(x(i),y(q.value)));c.stroke();c.fillStyle='#7c3f91';points.forEach((q,i)=>{c.beginPath();c.arc(x(i),y(q.value),4,0,Math.PI*2);c.fill()});c.fillStyle='#746b77';c.font='11px system-ui';c.textAlign='center';[0,Math.floor((points.length-1)/2),points.length-1].filter((v,i,a)=>a.indexOf(v)===i).forEach(i=>c.fillText(new Date(`${points[i].date}T12:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short'}),x(i),h-10));}
